<?php

/**
 * @file
 * The Smartling module file.
 */

define('SMARTLING_FIELDS_METHOD_KEY', '4');
define('SMARTLING_NODES_METHOD_KEY', '2');

define('SMARTLING_TRANSLATE_NODE', 'smartling_translate_node');
define('SMARTLING_ORIGINAL_NODE', 'smartling_original_node');
define('SMARTLING_ORIGINAL_WITHOUT_TRANSLATION_NODE', 'smartling_original_without_translation_node');

define('SMARTLING_STATUS_IN_QUEUE', 0);
define('SMARTLING_STATUS_IN_TRANSLATE', 1);
define('SMARTLING_STATUS_TRANSLATED', 2);
define('SMARTLING_STATUS_CHANGE', 3);
define('SMARTLING_STATUS_FAILED', 4);
define('SMARTLING_STATUS_EVENT_SEND_TO_UPLOAD_QUEUE', 'smartling_send_node_to_upload_queue');
define('SMARTLING_STATUS_EVENT_FAILED_UPLOAD', 'smartling_send_node_failed_upload');
define('SMARTLING_STATUS_EVENT_UPLOAD_TO_SERVICE', 'smartling_upload_node_to_service');
define('SMARTLING_STATUS_EVENT_DOWNLOAD_FROM_SERVICE', 'smartling_download_node_from_service');
define('SMARTLING_STATUS_EVENT_UPDATE_FIELDS', 'smartling_update_node_fields');
define('SMARTLING_STATUS_EVENT_NODE_ENTITY_UPDATE', 'check_status_in_node_entity_update');

define('SMARTLING_PRODUCTION_MODE', 'PRODUCTION');
define('SMARTLING_DEFAULT_API_URL', 'https://capi.smartling.com/v1');

include_once 'smartling.utils.inc';
include_once 'smartling_vbo_actions.inc';
include_once 'includes/smartling.workers.inc';
include_once 'includes/smartling.entity.inc';
include_once 'views/smartling.views.inc';
include_once 'entities/smartling.taxonomy.inc';
include_once 'entities/smartling.node.inc';
include_once 'entities/smartling.comments.inc';
include_once 'entities/smartling.user.inc';
include_once 'entities/smartling.generic_entity.inc';

/**
 * Implements hook_boot().
 */
function smartling_boot() {
  //smartling_register();
}

/**
 * Implements hook_init().
 */
function smartling_init() {
  smartling_register();
}

/**
 * Implements hook_flush_caches().
 */
function smartling_flush_caches() {
  // In some context such as module activation, the boot method is not called so
  // the component is never registered with the class loader. This cause
  // troubles as we need the class definition when bootstrapping.
  smartling_register();
  return array();
}

/**
 * Registers smartling and dependencies name-space with the class loader.
 */
function smartling_register() {
  // Activates the class loader.
  $loader = drupal_classloader();
  $loader->registerNamespace('Drupal\smartling\Alters', __DIR__ . '/lib');
  $loader->registerNamespace('Drupal\smartling\Log', __DIR__ . '/lib');
  $loader->registerNamespace('Drupal\smartling\Settings', __DIR__ . '/lib');
  $loader->registerNamespace('Drupal\smartling\Processors', __DIR__ . '/lib');
  $loader->registerNamespace('Drupal\smartling\FieldProcessors', __DIR__ . '/lib');

}

/**
 * Implements hook_menu().
 */
function smartling_menu() {
  $items = array();

  $items['admin/config/regional/smartling'] = array(
    'title' => 'Smartling settings',
    'weight' => -99,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'smartling.admin.inc',
    'page callback' => 'smartling_admin_configuration_view',
    'access arguments' => array('administer smartling'),
  );

  $items['smartling'] = array(
    'title' => 'Smartling settings',
    'type' => MENU_CALLBACK,
    'page callback' => 'smartling_download_translate_simple_callback',
    'page arguments' => array(2, 3),
    'access arguments' => array('administer smartling'),
  );

  $items['smartling/callback/%'] = array(
    'title' => 'Smartling push',
    'type' => MENU_CALLBACK,
    'page callback' => 'smartling_push_callback',
    'access callback' => 'smartling_push_callback_access',
    'access arguments' => array(2),
  );

  $items['admin/config/regional/smartling/manual-management'] = array(
    'title' => 'Smartling manual translation management',
    'description' => 'Here you can send node to smartling or get translation from smartling for specific node if available',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('smartling_manual_management_form'),
    'access arguments' => array('administer smartling'),
    'file' => 'smartling.pages.inc',
  );

  return $items;
}

/**
 * Simple menu callback.
 *
 * Menu callback to register smartling paths in
 * menu router, to avoid problems with fast_404 module.
 *
 * @return string
 *   Return empty string.
 */
function smartling_download_translate_simple_callback() {
  return '';
}

/**
 * Implements hook_permission().
 */
function smartling_permission() {
  $permissions = array(
    'administer smartling' => array(
      'title' => t('Administer Smartling'),
      'description' => t('Access the administrative settings for the module.'),
    ),
    'administer smartling_entity_data entities' => array(
      'title' => t('Administer Smartling Entity Data entities'),
    ),
    'view any smartling_entity_data entity' => array(
      'title' => t('View any Smartling Entity Data entity'),
    ),
    'edit any smartling_entity_data entity' => array(
      'title' => t('Edit any Smartling Entity Data entity'),
    ),
    'create smartling_entity_data entities' => array(
      'title' => t('Create Smartling Entity Data Entities'),
    ),
  );
  return $permissions;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see smartling_field_settings_update_submit()
 */
function smartling_form_entity_translation_translatable_form_alter(&$form, &$form_state) {
  $form['#submit'][] = 'smartling_field_settings_update_submit';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function smartling_form_title_field_replacement_form_alter(&$form, &$form_state) {
  $form['#submit'][] = 'smartling_title_field_replacement_submit';
  $form['#submit'] = array_reverse($form['#submit']);
}

/**
 * Title field replacement form - Form Submit.
 *
 * @param array $form
 *   FAPI array.
 * @param array $form_state
 *   FAPI array.
 */
function smartling_title_field_replacement_submit(array $form, array &$form_state) {
  $smartling_settings = smartling_settings_get_handler();

  $entity_type = $form['#entity_type'];
  $bundle      = $form['#bundle'];
  $field_name  = $form['#field_name'];

  switch ($entity_type) {
    case 'node':
      if (smartling_nodes_method($bundle) && ($field_name == 'title')) {
        $node_settings = $smartling_settings->nodeGetFieldsSettingsByBundle($bundle);
        $property_field = $field_name . '_property_field';
        if (isset($node_settings[$property_field])) {
          $smartling_settings->deleteSingleFieldFromSettings($entity_type, $bundle, $field_name . '_property_field');
          $smartling_settings->addSingleFieldToSettings($entity_type, $bundle, $field_name . '_field');
        }
      }
      break;

    case 'taxonomy_term':
      $vocabulary = taxonomy_vocabulary_machine_name_load($bundle);
      $vocabulary_mode = i18n_taxonomy_vocabulary_mode($vocabulary);
      if (($vocabulary_mode == I18N_MODE_TRANSLATE) && in_array($field_name, array('name', 'description'))) {
        $term_settings = $smartling_settings->taxonomyTermGetFieldsSettingsByBundle($bundle);
        $property_field = $field_name . '_property_field';
        if (isset($term_settings[$property_field])) {
          $smartling_settings->deleteSingleFieldFromSettings($entity_type, $bundle, $field_name . '_property_field');
          $smartling_settings->addSingleFieldToSettings($entity_type, $bundle, $field_name . '_field');
        }
      }
      break;

    default:
      break;
  }
}

/**
 * Smartling field settings update form - Form Submit.
 *
 * If a translation for the field was turned off, remove
 * the field from the configuration node smartling.
 *
 * @param array $form
 *   FAPI array.
 * @param array $form_state
 *   FAPI array.
 */
function smartling_field_settings_update_submit(array $form, array &$form_state) {

  if (($form_state['values']['translatable'] == 1) && ($form_state['values']['confirm'] == 1) && !empty($form_state['field']['bundles'])) {
    $smartling_settings = smartling_settings_get_handler();
    foreach ($form_state['field']['bundles'] as $entity_type => $bundles) {
      foreach ($bundles as $bundle) {
        $smartling_settings->deleteSingleFieldFromSettings($entity_type, $bundle, $form_state['field']['field_name']);
      }
    }
  }
}

/**
 * Smartling download and translate form - Form Submit.
 *
 * @param array $form
 *   FAPI array.
 * @param array $form_state
 *   FAPI array.
 */
function smartling_download_translate_form_submit(array $form, array &$form_state) {
  $log = smartling_log_get_handler();

  if (count(array_filter($form_state['values']['target'])) !== 0) {
    foreach ($form_state['values']['target'] as $d_locale) {
      if ($d_locale === 0) {
        continue;
      }

      $entity_wrapper = entity_metadata_wrapper($form['#entity_type'], $form['#entity']);


      $log->setMessage('Smartling start force download translated file for node id - @nid, locale - @locale')
        ->setVariables(array(
          '@nid' => $entity_wrapper->getIdentifier(),
          '@locale' => $d_locale,
        ))
        // @todo remove hardcoded link. We have function linkToContent()
        ->setLink(l(t('Edit node'), 'node/' . $entity_wrapper->getIdentifier() . '/edit'))
        ->execute();

      $entity_data = smartling_entity_load_by_conditions(array(
        'rid' => $entity_wrapper->getIdentifier(),
        'bundle' => $entity_wrapper->getBundle(),
        'target_language' => $d_locale,
      ));

      if (!$entity_data) {
        $log->setMessage('Smartling FAIL force download translated file for node id - @nid, locale - @locale')
          ->setVariables(array(
            '@nid' => $entity_wrapper->getIdentifier(),
            '@locale' => $d_locale,
          ))
          // @todo remove hardcoded link. We have function linkToContent()
          ->setLink(l(t('Edit node'), 'node/' . $entity_wrapper->getIdentifier() . '/edit'))
          ->execute();
        drupal_set_message(t('You did not send this entity to translate or that the task is in queue. Language - @language', array('@language' => $d_locale)));
        return;
      }

      smartling_queue_download_update_translated_item_process($entity_data->eid);
    }
  }

  if (isset($_GET['destination'])) {
    unset($_GET['destination']);
    drupal_goto(current_path());
  }
}

/**
 * Implements hook_views_api().
 */
function smartling_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_cron().
 */
function smartling_cron() {
  $query = new EntityFieldQuery();
  $entities = $query->entityCondition('entity_type', 'smartling_entity_data')
    ->propertyCondition('progress', 100, '<>')
    // @TODO move 'original' to constant.
    ->propertyCondition('target_language', 'original', '<>')
    ->execute();

  if (!empty($entities['smartling_entity_data'])) {
    $log = smartling_log_get_handler();
    $smartling_queue = DrupalQueue::get('smartling_check_status');
    $smartling_queue->createQueue();
    foreach (array_keys($entities['smartling_entity_data']) as $eid => $queue_item) {
      if (!empty($queue_item->file_name)) {

        $smartling_queue->createItem($eid);
        $log->setMessage('Add item to "smartling_check_status" queue. Smartling entity data id - @eid, related entity id - @rid, entity type - @entity_type')
          ->setVariables(array(
            '@eid' => $queue_item->eid,
            '@rid' => $queue_item->rid,
            '@entity_type' => $queue_item->entity_type,
          ))
          ->execute();
      }
      elseif ($queue_item->status != 0) {
        $log->setMessage('Original file name is empty. Smartling entity data id - @eid, related entity id - @rid, entity type - @entity_type')
          ->setVariables(array(
            '@eid' => $queue_item->eid,
            '@rid' => $queue_item->rid,
            '@entity_type' => $queue_item->entity_type,
          ))
          ->setSeverity(WATCHDOG_WARNING)
          ->execute();
      }
    }
  }
}

/**
 * Implements hook_cron_alter().
 */
function smartling_cron_alter(&$hooks) {
  if (isset($hooks['smartling_cron'])) {
    $hooks['smartling_cron']['title'] = t('Add items to "smartling_check_status" queue.');
    $hooks['smartling_cron']['scheduler']['simple']['rules'][0] = '0+@ */3 * * *';
  }
  if (isset($hooks['queue_smartling_upload'])) {
    $hooks['queue_smartling_upload']['title'] = t('Upload files with original content.');
    $hooks['queue_smartling_upload']['scheduler']['simple']['rules'][0] = '* * * * *';
  }
  if (isset($hooks['queue_smartling_check_status'])) {
    $hooks['queue_smartling_check_status']['title'] = t('Check translation progress of files.');
    $hooks['queue_smartling_check_status']['scheduler']['simple']['rules'][0] = '* * * * *';
  }
  if (isset($hooks['queue_smartling_download'])) {
    $hooks['queue_smartling_download']['title'] = t('Download files with translations.');
    $hooks['queue_smartling_download']['scheduler']['simple']['rules'][0] = '* * * * *';
  }
}

/**
 * Implements hook_cron_queue_info().
 */
function smartling_cron_queue_info() {
  $queues['smartling_upload'] = array(
    'worker callback' => 'smartling_queue_send_to_translate_process',
  );
  $queues['smartling_check_status'] = array(
    'worker callback' => 'smartling_queue_check_status_process',
  );
  $queues['smartling_download'] = array(
    'worker callback' => 'smartling_queue_download_update_translated_item_process',
  );

  return $queues;
}

/**
 * Implements hook_entity_update().
 */
function smartling_entity_update($entity, $type) {

  $entity_wrapper = entity_metadata_wrapper($type, $entity);
  $rid = $entity_wrapper->getIdentifier();
  $bundle = $entity_wrapper->getBundle();

  $smartling_entity_data = FALSE;
  if (smartling_supported_type($type, $bundle)) {
    $smartling_entity_data = smartling_entity_load_all_by_conditions(array(
      'rid' => $rid,
      'bundle' => $bundle,
    ));
  }

  if ($smartling_entity_data !== FALSE && is_array($smartling_entity_data)) {
    $sm_data       = current($smartling_entity_data);
    $processor     = smartling_get_entity_processor($sm_data);
    $content_array = $processor->getTranslatableContent();
    $content_hash  = md5(serialize($content_array));

    foreach ($smartling_entity_data as $smartling_entity) {
      $old_content_hash = $smartling_entity->content_hash;

      if (!empty($old_content_hash) && ($content_hash !== $old_content_hash) && !isset($entity->send_to_smartling)) {
        smartling_set_translation_status($smartling_entity, SMARTLING_STATUS_EVENT_NODE_ENTITY_UPDATE);
      }
      $smartling_entity_changed = smartling_entity_data_load($smartling_entity->eid);
      $smartling_entity_changed->content_hash = $content_hash;
      smartling_entity_data_save($smartling_entity_changed);
    }
  }
}

/**
 * Implements hook_entity_delete().
 */
function smartling_entity_delete($entity, $type) {
  $entity_wrapper = entity_metadata_wrapper($type, $entity);
  $rid = $entity_wrapper->getIdentifier();

  db_delete('smartling_entity_data')
    ->condition('rid', $rid)
    ->condition('entity_type', $type)
    ->execute();
}

/**
 * Implements hook_views_pre_render().
 */
function smartling_views_pre_render(&$view) {
  if ($view->name == 'smartling_submissions') {
    drupal_add_library('system', 'ui.progressbar');
    drupal_add_js(drupal_get_path('module', 'smartling') . '/js/smartling_admin.js');
  }
}

/**
 * Implements hook_action_info().
 */
function smartling_action_info() {
  return array(
    'smartling_do_translate_action' => array(
      'type' => 'system',
      'label' => t('Smartling entity translate.'),
      'configurable' => TRUE,
      'triggers' => array('any'),
    ),
    'smartling_do_download_translation_action' => array(
      'type' => 'smartling_entity_data',//'entity',
      'label' => t('Download translated content elements.'),
      'behavior' => array('changes_property'),
      'configurable' => FALSE,
      'vbo_configurable' => TRUE,
      'triggers' => array('any'),
    ),
    'smartling_do_resend_translation_action' => array(
      'type' => 'smartling_entity_data',//'entity',
      'label' => t('Resend selected content elements for translation.'),
      'behavior' => array('changes_property'),
      'configurable' => FALSE,
      'vbo_configurable' => TRUE,
      'triggers' => array('any'),
    ),
  );
}

/**
 * Smartling push callback access function.
 *
 * @param string $key
 *   Drupal cron key.
 *
 * @return bool
 *   Return TRUE if user have access.
 */
function smartling_push_callback_access($key) {
  return (variable_get('cron_key', 'drupal') == $key && empty($_POST));
}

/**
 * Smartling push callback function.
 */
function smartling_push_callback() {
  $log = smartling_log_get_handler();
  $log->setMessage('Smartling starts to process callback request')->execute();

  if (isset($_GET['locale']) && isset($_GET['fileUri'])) {
    $d_locale = check_plain(smartling_convert_locale_smartling_to_drupal($_GET['locale']));
    $file_uri = smartling_clean_filename($_GET['fileUri']);

    $log->setMessage('Smartling get parameters: locale - @locale, fileUri - @fileUri')
      ->setVariables(array('@locale' => $d_locale, '@fileUri' => $file_uri))
      ->execute();

    $entity_data = smartling_entity_load_by_conditions(array(
      'target_language' => $d_locale,
      'file_name' => $file_uri,
    ));

    if ($entity_data != FALSE) {
      if (module_exists('rules')) {
        rules_invoke_event('smartling_callback_call_event', $d_locale, $file_uri);
      }

      smartling_queue_download_update_translated_item_process($entity_data->eid);

      $log->setMessage('The callback function smartling downloaded translation for bundle - @bundle, entity id - @rid, language - @language')
        ->setVariables(array(
          '@bundle' => $entity_data->bundle,
          '@rid' => $entity_data->rid,
          '@language' => $d_locale,
        ))
        ->setLink(l(t('Edit node'), 'node/' . $entity_data->rid . '/edit'))
        ->execute();
    }
    elseif ($entity_data == FALSE) {
      $log->setMessage('For the parameters locale - @locale and fileUri - @fileUri entity smartling are missing')
        ->setVariables(array('@locale' => $d_locale, '@fileUri' => $file_uri))
        ->setSeverity(WATCHDOG_WARNING)
        ->execute();
      // 404.
    }
  }
  else {
    $params = array('locale', 'fileUri');
    foreach ($params as $param) {
      if (!isset($_GET[$param])) {
        $log->setMessage('Smartling GET parameter "@param_name" are missing')
          ->setVariables(array('@param_name' => $param))
          ->setSeverity(WATCHDOG_WARNING)
          ->execute();
        // 404.
      }
    }
  }
}

/**
 * Implements hook_smartling_settings_form_info().
 *
 * @return array
 */
function smartling_smartling_settings_form_info() {
  $forms = array(
    'smartling_admin_account_info_settings_form' => t('Account info'),
    'smartling_admin_node_translation_settings_form' => t('Nodes settings'),
    'smartling_admin_entities_translation_settings_form' => t('Entities settings'),
  );

  if (module_exists('taxonomy')) {
    $forms['smartling_admin_taxonomy_translation_settings_form'] = t('Taxonomy vocabularies and fields');
  }

  $forms['smartling_admin_log_info_settings_form'] = t('Smartling log');

  if (module_exists('smartling_load_test')) {
    $forms['smartling_admin_dev_settings_form'] = t('Dev settings');
  }
  if (module_exists('smartling_reference')) {
    $forms['smartling_admin_reference_settings_form'] = t('References settings');
  }

  return $forms;
}