; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.23"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[background_process][subdir] = "contrib"
projects[background_process][version] = "1.14"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"

projects[defaultcontent][subdir] = "contrib"
projects[defaultcontent][version] = "1.0-alpha9"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.2"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0"

projects[i18n][subdir] = "contrib"
projects[i18n][version] = "1.10"

projects[progress][subdir] = "contrib"
projects[progress][version] = "1.4"

projects[title][subdir] = "contrib"
projects[title][version] = "1.0-alpha7"

projects[ultimate_cron][subdir] = "contrib"
projects[ultimate_cron][version] = "1.9"

projects[ultimate_cron_queue_scaler][subdir] = "contrib"
projects[ultimate_cron_queue_scaler][version] = "1.0"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.3"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"


