<?php

/**
 * @file
 * Code for the Smartling reports feature.
 */
include_once 'smartling_reports.features.inc';

/**
 * Implements hook_menu().
 */
function smartling_reports_menu() {
  $items = array();

  $items['admin/content/smartling'] = array(
    'title' => 'Submissions',
    'description' => 'Submissions',
    'weight' => 101,
    'access arguments' => array('administer smartling'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function smartling_reports_menu_alter(&$items) {
  if (!empty($items['admin/content/smartling/report-completed'])) {
    $items['admin/content/smartling']['page callback'] = $items['admin/content/smartling/report-completed']['page callback'];
    $items['admin/content/smartling']['page arguments'] = $items['admin/content/smartling/report-completed']['page arguments'];
    $items['admin/content/smartling']['load arguments'] = $items['admin/content/smartling/report-completed']['load arguments'];
    $items['admin/content/smartling/report-completed']['type'] = MENU_DEFAULT_LOCAL_TASK;
  }
}

function smartling_reports_preprocess_views_view_table(&$vars) {
  if ($vars['view']->name != 'smartlig_report') {
    return;
  }

  $rows = $vars['view']->result;
  if (!empty($rows) && is_array($rows)) {
    foreach($rows as $k => $v) {
      if ($v->smartling_entity_data_status == SMARTLING_STATUS_FAILED) {
        $vars['row_classes'][$k][] = 'failed_status';
      }
    }
    drupal_add_css(drupal_get_path('module', 'smartling') . '/css/smartling_admin.css');
  }
}