<?php

/**
 * @file
 * Smartling context.
 */

/**
 * Implements hook_menu().
 */
function smartling_translation_context_menu() {
  $menu = array();

  // context/authorize?apiKey=XXX&projectId=XXX
  $menu['context/authorize'] = array(
    'type' => MENU_CALLBACK,
    'file' => 'includes/context_authorize.inc',
    'page callback' => 'smartling_translation_context_authorize',
    'access callback' => TRUE,
    'delivery callback' => 'smartling_translation_context_deliver_json',
  );

  // context/expireToken?token=XXX
  $menu['context/expireToken'] = array(
    'type' => MENU_CALLBACK,
    'file' => 'includes/context_authorize.inc',
    'page callback' => 'smartling_translation_context_token_expire',
    'access callback' => TRUE,
    'delivery callback' => 'smartling_translation_context_deliver_json',
  );

  // context/html?fileuri=XXX.xml&token=XXX
  $menu['context/html'] = array(
    'type' => MENU_CALLBACK,
    'file' => 'includes/context_html.inc',
    'page callback' => 'smartling_translation_context_html',
    'access callback' => 'smartling_translation_context_access',
    'delivery callback' => 'smartling_translation_context_deliver_json',
  );

  // context/resource?fileuri=/css/main.css&token=XXX
  $menu['context/resource'] = array(
    'type' => MENU_CALLBACK,
    'file' => 'includes/context_resource.inc',
    'page callback' => 'smartling_translation_context_resource',
    'access callback' => TRUE,
    'delivery callback' => 'smartling_translation_context_deliver_as_is',
  );

  return $menu;
}

/**
 * Smartling context access function.
 *
 * @return bool
 *   Return access result.
 */
function smartling_translation_context_access() {
  return TRUE;
}

/**
 * Deliver json callback.
 *
 * @param mixed $data
 *   Json data.
 */
function smartling_translation_context_deliver_json($data) {
  print json_encode($data);
}

/**
 * Deliver as is.
 *
 * @param mixed $data
 *   Data.
 */
function smartling_translation_context_deliver_as_is($data) {
  print $data;
}
