<?php

/**
 * @file
 * Code for the nodes preparation for translation feature.
 */

function smartling_entity_utils_action_info() {
  return array(
    'smartling_entity_utils_translate_prepare_action' => array(
      'type' => 'entity',
      'label' => t('Prepare content items for translation.'),
      'behavior' => array('changes_property'),
      'configurable' => FALSE,
      'vbo_configurable' => TRUE,
      'triggers' => array('any'),
    ),
  );
}

function smartling_entity_utils_translate_prepare_action_form() {
  $form = array();

  $form['confirm'] = array(
    '#type' => 'checkbox',
    '#title' => t('I confirm that I understand that this action is irrevertible. And that I have a backup for my data (DB).'),
  );

  return $form;
}

function smartling_entity_utils_translate_prepare_action_validate($form, $form_state) {
  if (!@$form['confirm']['#value']) {
    form_set_error('confirm', t('Please confirm explicitly if you want to continue.'));
  }

  if (!user_access('bypass content access control')) {
    form_set_error('confirm', t('Sorry, but you need "Bypass content access control" permissions to execute this operation. Please ask administrator to grant it to you.'));
  }
}

function smartling_entity_utils_translate_prepare_action_submit($form, $form_state) {
  return array();
}

function smartling_entity_utils_translate_prepare_action(&$entity, $context) {
  $default_lang = language_default()->language;

  if (in_array($entity->language, array(LANGUAGE_NONE, $default_lang))) {
    $entity_wrapper = entity_metadata_wrapper($context['entity_type'], $entity);
    $bundle = $entity_wrapper->getBundle();
    smartling_entity_utils_translate_router($entity, $context['entity_type'], $bundle, $default_lang);
  }
  else {
    //todo: Add logging here
  }
}

function smartling_entity_utils_translate_router($entity, $type, $bundle, $default_lang) {
  if (!smartling_supported_type($type, $bundle)) {
    return;
  }
  $allowed_fields = smartling_settings_get_handler()->getFieldsSettingsByBundle($type, $bundle);

  smartling_entity_utils_update_to_fields_translate_method($entity, $type, $default_lang, $allowed_fields);
}

function smartling_entity_utils_update_to_fields_translate_method($entity, $type, $default_language, $allowed_fields) {
  if ($default_language == LANGUAGE_NONE) {
    return FALSE;
  }

  $field_langs = field_language($type, $entity);

  if (!in_array($default_language, $field_langs) && !in_array(LANGUAGE_NONE, $field_langs)) {
    return FALSE;
  }

  foreach($field_langs as $field => $lang) { // go through ALL field of this node
    if (($lang == LANGUAGE_NONE) && (in_array($field, $allowed_fields))) { // if the field is in the wrong language
      $items = field_get_items($type, $entity, $field, $lang); // get all field values
      if (!empty($items)) {
        $entity->{$field}[$default_language] = $items; // put it under language neutral
        unset($entity->{$field}[$lang]); // remove the old language
      }
    }
  }
  $entity->language = $default_language;//LANGUAGE_NONE; // set the node language to neutral
}

function smartling_entity_utils_views_template($entity_type) {
  $entity_info = entity_get_info($entity_type);
  $base_table = $entity_info['base table'];
  $title_field = $entity_info['entity keys']['label'];
  $id_field = $entity_info['entity keys']['id'];


  $view = new view();
  $view->name = 'prepare_' . $entity_type . '_for_translation';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = $base_table;
  $view->human_name = 'Prepare ' . $entity_type . ' for translation';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = $entity_type . ' utils';
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['access']['perm'] = 'bypass node access';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '25';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['style_plugin'] = 'table';

  /* Field: Bulk operations: User */
  $handler->display->display_options['fields']['views_bulk_operations']['id'] = 'views_bulk_operations';
  $handler->display->display_options['fields']['views_bulk_operations']['table'] = $base_table;
  $handler->display->display_options['fields']['views_bulk_operations']['field'] = 'views_bulk_operations';
  $handler->display->display_options['fields']['views_bulk_operations']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['views_bulk_operations']['vbo_settings']['display_type'] = '1';
  $handler->display->display_options['fields']['views_bulk_operations']['vbo_settings']['enable_select_all_pages'] = 1;
  $handler->display->display_options['fields']['views_bulk_operations']['vbo_settings']['force_single'] = 0;
  $handler->display->display_options['fields']['views_bulk_operations']['vbo_settings']['entity_load_capacity'] = '10';
  $handler->display->display_options['fields']['views_bulk_operations']['vbo_operations'] = array(
    'action::smartling_entity_utils_translate_prepare_action' => array(
      'selected' => 1,
      'postpone_processing' => 1,
      'skip_confirmation' => 0,
      'override_label' => 1,
      'label' => 'Prepare ' . $entity_type . '(s) for translation',
    ),
  );
  /* Field: User: Name */
  $handler->display->display_options['fields'][$title_field]['id'] = $title_field;
  $handler->display->display_options['fields'][$title_field]['table'] = $base_table;
  $handler->display->display_options['fields'][$title_field]['field'] = $title_field;
  $handler->display->display_options['fields'][$title_field]['label'] = '';
  $handler->display->display_options['fields'][$title_field]['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields'][$title_field]['alter']['ellipsis'] = FALSE;
  /* Field: User: Language */
  $handler->display->display_options['fields']['language']['id'] = 'language';
  $handler->display->display_options['fields']['language']['table'] = $base_table;
  $handler->display->display_options['fields']['language']['field'] = 'language';
  //$handler->display->display_options['fields']['language']['link_to_user'] = FALSE;
  /* Sort criterion: User: Created date */
  $handler->display->display_options['sorts'][$id_field]['id'] = $id_field;
  $handler->display->display_options['sorts'][$id_field]['table'] = $base_table;
  $handler->display->display_options['sorts'][$id_field]['field'] = $id_field;
  $handler->display->display_options['sorts'][$id_field]['order'] = 'DESC';

  /* Display: Page */
  $handler = $view->new_display('page', 'Page', 'page');
  $handler->display->display_options['path'] = 'admin/config/regional/smartling/prepare_' . $entity_type . '_for_translation';
}