<?php

/**
 * @file
 * Code for the smartling_push.
 */

/**
 * Implements hook_menu().
 */
function smartling_push_menu() {
  $items = array();

  $items['smartling-push'] = array(
    'title' => 'Smartling push',
    'type' => MENU_CALLBACK,
    'page callback' => 'smartling_push_callback',
    'access callback' => TRUE,
  );

  return $items;
}

function smartling_push_callback() {
  $param1 = 1;

  if (isset($_GET['param1'])) {
    $param1 = check_plain($_GET['param1']);
  }

  return $param1;
}
