<?php

function smartling_content_utils_action_info() {
  return array(
    'smartling_content_utils_my_custom_action' => array(
      'type' => 'node',
      'label' => t('Search and replace text in a field'),
      'behavior' => array('changes_property'),
      'configurable' => FALSE,
      //'vbo_configurable' => TRUE,
      'triggers' => array('any'),
    ),
  );
}

function smartling_content_utils_my_custom_action_form() {
  return array();
}

function smartling_content_utils_my_custom_action_form_submit() {
  return TRUE;
}

function smartling_content_utils_my_custom_action(&$node, $context) {
  $message = t('Node title is %title. Sincerely, %hero', array(
    '%title' => $node->title,
    '%hero' => $context['hero'],
  ));
  drupal_set_message($message);
}

function update_node_language($node) {
    //$type = $node->type; // get the content type
    $field_langs = field_language('node', $node); // get the language of each field
    foreach($field_langs as $field => $lang) { // go through ALL field of this node
      if ($lang != LANGUAGE_NONE) { // if the field is in the wrong language
        $items = field_get_items('node',$node,$field,$lang); // get all field values
        if (!empty($items)) {
          $node->{$field}[LANGUAGE_NONE] = $items; // put it under language neutral
          unset($node->{$field}[$lang]); // remove the old language
        }
      }
    }
    $node->language = LANGUAGE_NONE; // set the node language to neutral
    //node_save($node); // commit changes
}