<?php

function smartling_translate_page_popup_boot() {

}
/**
 * Implements hook_flush_caches().
 */
function smartling_translate_page_popup_flush_caches() {
//  $loader = drupal_classloader();
//  $loader->registerNamespace('Drupal\smartling_translate_page_popup\Forms', __DIR__ . '/lib');
  drupal_classloader_register('Drupal\smartling_translate_page_popup\Forms', __DIR__ . '/lib');
}

function smartling_translate_page_popup_init() {
  //$loader = drupal_classloader();
  //$loader->registerNamespace('Drupal\smartling_translate_page_popup\Forms', __DIR__ . '/lib');
  drupal_classloader_register('Drupal\smartling_translate_page_popup\Forms', __DIR__ . '/lib');

}

/*
 * Implements hook_entity_load().
 */
function smartling_translate_page_popup_entity_load($entities, $type) {
  if (!user_access('administer smartling') || (language_default('language') != field_valid_language(NULL, FALSE)) || path_is_admin(current_path())) {
    return;
  }

  $language_default = language_default()->language;
  foreach ($entities as $entity) {
    if (!in_array(entity_language($type, $entity), array($language_default, LANGUAGE_NONE))) {
      continue;
    }

    $wrapper = entity_metadata_wrapper($type, $entity);
    $bundle = $wrapper->getBundle();
    if (smartling_translate_fields_configured($bundle, $type)) {
      $id = $wrapper->getIdentifier();
      $title = $wrapper->Label();

      $_SESSION['smartling']['page_entities'][$id . '_||_' . $type] = $title;
    }
  }
}

function smartling_translate_page_popup_page_alter(&$page) {
  if (!user_access('administer smartling') || (language_default('language') != field_valid_language(NULL, FALSE)) || path_is_admin(current_path())) {
    return;
  }

  $form_state = array();
  try {
    $page['page_bottom']['smartling_translation_form'] = drupal_build_form('smartling_translate_page_popup_form', $form_state);
  } catch (\Exception $e) {
    $page['page_bottom']['smartling_translation_form'] = array();

    smartling_log_get_handler()->error('Caught exception: ' . $e->getMessage());
  }

}

function smartling_translate_page_popup_form($form, $form_state) {
  if (!function_exists('drupal_container') || !drupal_container()->has('smartling.forms.translate_page_popup')) {
    return;
  }

  return drupal_container()->get('smartling.forms.translate_page_popup')->buildForm($form, $form_state);
}

function smartling_translate_page_popup_form_submit($form, $form_state) {
  return drupal_container()->get('smartling.forms.translate_page_popup')->submitForm($form, $form_state);
}
